/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.keene.mepbm.model;

/**
 *
 * @author nate
 */
public enum CombatArtifact {
    GORDUR (500, "Gordur"),
    ANGIAN (500, "Angian"),
    GURTHDUR (500, "Gurthdur"),
    DURCRIST (500, "Durcrist"),
    E_VORONWE (500, "E Voronwe"),
    RUNYA (500, "Runya"),
    STING (500, "Sting"),
    TURANTIR (500, "Turantir"),
    STONE_MACE_OF_SETMAENEN (500, "Stone-mace of Setmaenen"),
    IRONFOOTS_HAMMER (500, "Ironfoot's Hammer"),
    AIR_CLEAVER (500, "Air-Cleaver"),
    YELLOW_HAMMER (500, "Yellow Hammer"),
    STORMLESS_BOW (500, "Stormless Bow"),
    RING_OF_ANGRENOST (500, "Ring of Angrenost"),
    SNOW_HAMMER (500, "Snow Hammer"),
    SPEAR_OF_FOLLOWING (500, "Spear of Following"),
    DAGGER_OF_GREEN_WISDOM (500, "Dagger of Green Wisdom"),
    FOHNRAD (500, "Fohnrad"),
    GILDAGOR (500, "Gildagor"),
    HORSE_SLAYER (500, "Horse-slayer"),
    HORSE_TAMER (500, "Horse-Tamer"),
    HUE_CHANGER (500, "Hue Changer"),
    MACE_OF_THE_HUNTSMAN (500, "Mace of the Huntsman"),
    MOTHRAS (500, "Mothras"),
    NAVORN (500, "Navorn"),
    NIGHT_PIERCER (500, "Night-piercer"),
    BELIEVERS_BANE (500, "Believer's Bane"),
    BOW_OF_THUNDER_AND_BONE (500, "Bow of Thunder & Bone"),
    CIRMEGIL (500, "Cirmegil"),
    CRAIG_OLF_TI (500, "Craig-olf-Ti"),
    BRODIC_SPEAR (500, "Brodic Spear"),
    CUBRAGOL (500, "Cubragol"),
    CULOK (500, "Culok"),
    CURARAN (500, "Curaran"),
    BURNING_BLADE (500, "Burning Blade"),
    ELFHEWER (500, "Elfhewer"),
    MORLHACH (500, "Morlhach"),
    ELFBANE (500, "Elfbane"),
    FLAILS_OF_HORSESLAYING (500, "Flails of Horseslaying"),
    ONGRUM (500, "Ongrum"),
    SWORD_OF_SOUL_REDUCING (500, "Sword of Soul Reducing"),
    STINGING_TONGUE (500, "Stinging Tongue"),
    THRAKURGHASH (500, "Thrakurghash"),
    RAUKAMBAR (750, "Raukambar"),
    GERSEBROC (750, "Gersebroc"),
    MAIKARAMA (750, "Maikarama"),
    AEGLIN (750, "Aeglin"),
    ANARMACIL (750, "Anarmacil"),
    AR_SIL (750, "Ar-Sil"),
    DAGNIRDRAUG (750, "Dagnirdraug"),
    DAINS_AXE (750, "Dain's Axe"),
    DURLACHIEL (750, "Durlachiel"),
    FOREST_BLADE (750, "Forest-blade"),
    GUTHWINE (750, "Guthwine"),
    ORC_SLAYER (750, "Orc Slayer"),
    ORCRIST (750, "Orcrist"),
    SCEPTRE_OF_HENT (750, "Sceptre of Hent"),
    SIL_MAEGIL (750, "Sil-Maegil"),
    TROLL_SLAYER (750, "Troll Slayer"),
    UNGOLRIST (750, "Ungolrist"),
    AERCRIST (750, "Aercrist"),
    WAR_DANCER (750, "War-dancer"),
    WATER_SKIMMER (750, "Water-skimmer"),
    USRIEV (750, "Usriev"),
    SWORD_OF_CLEAVING (750, "Sword of Cleaving"),
    STEWARDS_BLADE (750, "Steward's Blade"),
    ROMOQUENARO (750, "Romoquenaro"),
    NELDELHACH (750, "Neldelhach"),
    NIGHTFANG (750, "Nightfang"),
    HATRED_CURSE (750, "Hatred Curse"),
    KPRURIAN_BATTLE_MACE (750, "K'Prurian Battle Mace"),
    MACIRILLE (750, "Macirille"),
    MIGHTY_BLADE (750, "Mighty Blade"),
    MOON_AXE (750, "Moon Axe"),
    GHOSTBANE (750, "Ghostbane"),
    ELENRUTH (750, "Elenruth"),
    FIRE_MACE (750, "Fire Mace"),
    DURINS_AXE (750, "Durin's Axe"),
    CLOUD_BOW (750, "Cloud Bow"),
    CUBELEG (750, "Cubeleg"),
    AXE_OF_BROAGHA (750, "Axe of Braogha"),
    BLOOD_SPIKE (750, "Blood Spike"),
    BLOODRUNNER (750, "Bloodrunner"),
    CALRIS (750, "Calris"),
    CUIVIEGURTH (750, "Cuiviegurth"),
    DAWNSWORD (750, "Dawnsword"),
    FIRES_EDGE (750, "Fire's Edge"),
    NALLAGURTH (750, "Nallagurth"),
    VASAMACIL (750, "Vasamacil"),
    AEDRING (1000, "Aedring"),
    ARATOCAM (1000, "Aratocam"),
    DAERONS_RAPIER (1000, "Daeron's Rapier"),
    ELHACH (1000, "Elhach"),
    MORGURTH (1000, "Morgurth"),
    SICKLE_OF_THE_HEAVENS (1000, "Sickle of the Heavens"),
    SKULL_FLAIL (1000, "Skull Flail"),
    SULHELKA (1000, "Sulhelka"),
    ANDURIL (1250, "Anduril"),
    KIRRAUKO (1250, "Kirrauko"),
    BLUE_BOW (1250, "Blue Bow"),
    SPEAR_OF_BLADORTHIN (1250, "Spear of Bladorthin"),
    DURCARAK (1250, "Durcarak"),
    THUNDERS_EDGE (1250, "Thunder's Edge"),
    ARACU (1500, "Aracu"),
    CALNINQUE (1500, "Calninque"),
    ERIVAGIL (1500, "Erivagil"),
    FOAM_CLEAVER (1500, "Foam-cleaver"),
    GLOSOVAGIL (1500, "Glosovagil"),
    SAURONS_JAVELIN (1500, "Sauron's Javelin"),
    ARANRUTH (1750, "Aranruth"),
    CARANLHACH (1750, "Caranlhach"),
    RAUZGNAGLI (1750, "Rauzgnagli"),
    RINGIL (2000, "Ringil"),
    TROLL_CLEAVER (2000, "Troll-Cleaver"),
    SILMARUTH (2000, "Silmaruth"),
    TAURIN (2000, "Taurin"),
    FUINRAUKO (2000, "Fuinrauko"),
    ANCARUIN (2250, "Ancaruin"),
    BELTHRONDING (2250, "Belthronding"),
    ORCRING (2250, "Orcring"),
    ORCRUIN (2250, "Orcruin"),
    ANGUIREL (2250, "Anguirel"),
    GURTHANG (2250, "Gurthang"),
    MORMACIL (2250, "Mormacil");
    private final int damage;
    private final String name;
    
    CombatArtifact(int damage, String name){
        this.damage = damage;
        this.name = name;
    }
}
